centre-for-educational-technology/edidaktikum

- ed_answer/ed_answer.module
- ed_cluster/ed_cluster.module
- ed_cluster/includes/views/ed_cluster.views_default.inc
- ed_file/ed_file.module
- ed_learning_resource/ed_learning_resource_ajax.inc
- ed_q_portfolio/ed_q_portfolio.info
- ed_q_portfolio/ed_q_portfolio.install
- ed_q_portfolio/ed_q_portfolio.module
- ed_q_portfolio/js/ed_q_portfolio.js
- ed_task/ed_task.module
- ed_user_extra/ed_user_extra.module
- edidaktikum.js
- edidaktikum.module
> Preparing v1.6.2

- ed_q_portfolio/ed_q_portfolio.install
> Preparing v1.7.1

- ed_task/ed_task.install
- ed_task/ed_task.module
- ed_task/ed_task.pages_default.inc
- ed_user_extra/ed_user_extra.install
- ed_user_extra/ed_user_extra.module
> Preparing v1.7.3

- ed_cluster/ed_cluster.module
Includes "Not applicable" state for Task Manager
> Study groups related fixes and improvements 

- ed_dashboard/ed_dashboard.module
- edidaktikum.module
> Preparing v1.7.4

- ed_cluster/ed_cluster.pages_default.inc
- ed_learning_resource/ed_learning_resource.install
- ed_learning_resource/ed_learning_resource.module
- ed_learning_resource/ed_learning_resource.pages_default.inc
- ed_learning_resource/ed_learning_resource_functions.inc
> Preparing 1.7.4

- ed_cluster/ed_cluster.module
Added logic to get data for unseen resource types count of the group by
a certain user. Added logic to group menu items that should have been
affected. Made sure that similar queries are only ran once per page
load, provided group and user identifiers are the same (uses static
variable for that).
> References #524, feature fully implemented.

- ed_task/ed_task.install
- ed_task/ed_task.pages_default.inc
- ed_task/ed_task_functions.inc
Defined new field and instance. Added migration to create those, if not
yet present. Updated panel (edit). Field itself is not yet shown or used
anywhere.
> Resolves #660, field + migration + panel.

- ed_analytics/ed_analytics.info
- ed_analytics/modules/ed_xapi/ed_xapi.info
- ed_analytics/modules/ed_xapi/ed_xapi.install
- ed_analytics/modules/ed_xapi/ed_xapi.module
> Refernces #680, Initial implementation of xAPI for analytics.

- ed_dashboard/ed_dashboard.module
The issue was with semester months from previous year. Made sure that
code could hadle that. In case it is January and current month is not
January, then last year will be used.
> Resolves #687, updated logic.

- ed_cluster/ed_cluster.module
- edidaktikum.css
- edidaktikum.module
Requires these changes to theme https://github.com/centre-for-educational-technology/edidaktikum_theme/pull/78
> Resolves #711

- ed_answer/ed_answer.install
- ed_answer/ed_answer.module
- ed_blog/ed_blog.module
- ed_cluster/ed_cluster.module
- ed_cluster/ed_cluster.pages.inc
- ed_dashboard/ed_dashboard.module
- ed_file/ed_file.module
- edidaktikum.module
#690: Need to update module for translation fix to take effect
#729: changed lists
- drafts
- shared with me
- files
> Resolved #690, #729

- ed_cluster/ed_cluster.module
- ed_cluster/task_manager.css
- ed_file/css/file_listing_page.css
- ed_file/ed_file.module
- edidaktikum.css
- edidaktikum.module
> Moved filter button to the side in dashboard pages

- ed_cluster/ed_cluster.module
- ed_cluster/task_manager.css
- edidaktikum.css
#733 Added room between the dropdown and button in dashboard
#736 Fixed filter button
> Fixed #733 & #736 Changed button gap, fixed filter button

- ed_answer/ed_answer.install
Changed values and now using allowed_values_function instead of allowed_values
> Resolved #758

- ed_task/ed_task.module
lihtsalt mergen oma branchid uuesti 👍
> Resolved #748

- ed_answer/ed_answer.install
- ed_task/ed_task.module
- Added new sorting capabilities for task view, sort by title, group, due date, status (#748)
- Field display was set default translatable but should just be default, this fixes that (#780)
> Resolves #748, #780

- ed_answer/ed_answer.install
Pärast live panemist tuleb üle vaadata, kas kõigile sõnedele on eestikeelne tõlge olemas
> Resolved #797

- ed_answer/ed_answer.pages_default.inc
Adds user profile picture into answer panels.
https://github.com/centre-for-educational-technology/edidaktikum_theme/pull/101 is also necessary to make it look nice
> References centre-for-educational-technology/edidaktikum#779

- ed_answer/ed_answer.module
- ed_answer/ed_answer.pages_default.inc
This is also necessary https://github.com/centre-for-educational-technology/edidaktikum_theme/pull/103
> #779 Rearranged user image and name

- ed_cluster/ed_cluster.module
A small change to the curriculum title.
> Resolves #880, changed curriculum title.

- edidaktikum.admin.inc
- edidaktikum.module
- edidaktikum.variable.inc
> References #914, implemented front page message checkbox feature.

- edidaktikum.module
The issue was with the order of items and corresponding link elements. The code assumed that the order is the same and it was not.
> Resolves #947, made sure that listings for active and inactive groups are correct.
